### ISSUE TITLE
Number of Households

### ISSUE THREAD

**Issue by buzwells** [codeforkansascity/Property-Violations-Settlement#55]
Eric R suggests that we pull in number of households in order to compute a sort of rate of violations per household within tracts. This could provide some insight into the impact of violations.

**Comment by dwancura** [comment]
Will you be there tonight?  I’d like to talk about this, plus the number of violations per household which we’d talked about some before.

Dan

**Comment by buzwells** [comment]
Yes sir. I have to do our little two minute report out. I’m also finding more time to work on this now, and I’m anxious to keep making progress. I think we really have some good data to chew on now, even if we want to keep refining it.

**Comment by dwancura** [comment]
Agreed.  See you tonight.

Dan

**Comment by buzwells** [comment]
Created an initial version of the data with the household figures added (from census table B11001). Have not pushed the code yet.

**Comment by buzwells** [comment]
Pushed code. Closing now. Will add a new item if there are any issues detected with the new data.
